:arrow_up: Adding scaling section
eth-protocol-fellows/protocol-studies pull request #16
Opened 2024-02-15 10:49 UTC by GianfrancoBazzani

Hi guys, this PR adds a new section named Scalability. Added some notes on that and left few subsections to be completed. Let me know if there is any issue ^^.

2024-02-15 11:17 UTC, taxmeifyoucan commented
Thanks a lot for the contribution! I am thrilled to see the first page coming from community. I left a review, sorry if I was nitpicking too much but we can move it forward :)

2024-02-15 14:31 UTC, GianfrancoBazzani commented
Sorry @taxmeifyoucan i can't se your comments.

2024-02-15 18:56 UTC, taxmeifyoucan requested changes

2024-02-15 19:00 UTC, taxmeifyoucan commented
@GianfrancoBazzani  Sorry I didn't finish the review. Also I'd like to see other people interested in the same topic to chime in, feel free to share it in discord :)

2024-02-18 20:46 UTC, GianfrancoBazzani commented on docs/wiki/protocol/scalability.md
> +#### Split consensus from execution (The Merge).
Which section do you think that will be the correct place be for the merge event? maybe The Protocol - History?

2024-02-18 20:49 UTC, GianfrancoBazzani commented on docs/wiki/protocol/scalability.md
> +Consensus mechanics require most of validator nodes in the network to publicly agree on the next valid block. This directly affects the block latency, which is the time it takes for a new block to be
I re-writed a bit the section to be more Ethereum specific. LMK if there's any issue.

2024-02-25 21:12 UTC, GianfrancoBazzani commented on docs/wiki/protocol/scalability.md
> +#### Split consensus from execution (The Merge).
I moved it to The Protocol - History

2024-02-26 15:20 UTC, merged